datasources:
  default:
    connection:
      url: ${MONGO_URL}
    objectFiles:
      - "./src/**"
    appFiles:
      - "./src/**"
public:
  cfs:
    store: "local"
    local: 
      folder: "./storage"
plugins:
  - "@steedos/accounts"
  - "@steedos/plugin-enterprise"
tenant:
  enable_register: false
  enable_forget_password: false
  saas: false
  enable_password_login: true